{"name": "test_data_driven_testing[ndj@mailinator.com-a4iM2@qJaP7U4AS-Valid]", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <test_004_DDT.Test_Data_Driven object at 0x000001DC1984E720>\nsetup = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"d00952cbec43478dfb938b390fe195a1\")>, username = 'ndj@mailinator.com'\npassword = 'a4iM2@qJaP7U4AS', expected_result = 'Valid'\n\n    @pytest.mark.parametrize(\"username, password, expected_result\", get_exceldata(path, \"Sheet1\"))\n    def test_data_driven_testing(self, setup, username, password, expected_result):\n        self.logger.info(f\"Starting test for: {username}\")\n    \n        self.driver = setup\n        self.driver.maximize_window()\n    \n        try:\n            # Navigate to Login Page\n            self.driver.get(self.baseurl)\n            self.hp = Homepage(self.driver)\n            self.hp.clickmyaccount()\n            self.hp.clicklogin()\n            self.ma = My_Account_page(self.driver)\n    \n            # Perform Login\n            self.lp = Login(self.driver)\n            self.lp.click_email(username)\n            self.lp.click_password(password)\n            self.lp.click_login()\n    \n            # Capture Screenshot after Login\n            allure.attach(self.driver.get_screenshot_as_png(), name=f\"After_Login_{username}\",\n                          attachment_type=AttachmentType.PNG)\n    \n            # Validate Result\n            self.actual_result = self.lp.myaccount_page()\n            self.logger.info(f\"Actual: {self.actual_result}, Expected: {expected_result}\")\n            if self.actual_result.strip().lower() in [\"exceeded\",\"unknown\"]:\n                self.actual_result = \"Invalid\"\n            # Assert and Capture Failures\n            if self.actual_result.strip().lower() == expected_result.strip().lower():\n                self.logger.info(f\"Test Passed for {username}\")\n                assert True\n            else:\n                self.logger.error(f\"Test Failed for {username}\")\n                allure.attach(self.driver.get_screenshot_as_png(), name=f\"Failure_{username}\",\n                              attachment_type=AttachmentType.PNG)\n>               assert False\nE               assert False\n\ntestCases\\Data Driven Test\\test_004_DDT.py:58: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <test_004_DDT.Test_Data_Driven object at 0x000001DC1984E720>\nsetup = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"d00952cbec43478dfb938b390fe195a1\")>, username = 'ndj@mailinator.com'\npassword = 'a4iM2@qJaP7U4AS', expected_result = 'Valid'\n\n    @pytest.mark.parametrize(\"username, password, expected_result\", get_exceldata(path, \"Sheet1\"))\n    def test_data_driven_testing(self, setup, username, password, expected_result):\n        self.logger.info(f\"Starting test for: {username}\")\n    \n        self.driver = setup\n        self.driver.maximize_window()\n    \n        try:\n            # Navigate to Login Page\n            self.driver.get(self.baseurl)\n            self.hp = Homepage(self.driver)\n            self.hp.clickmyaccount()\n            self.hp.clicklogin()\n            self.ma = My_Account_page(self.driver)\n    \n            # Perform Login\n            self.lp = Login(self.driver)\n            self.lp.click_email(username)\n            self.lp.click_password(password)\n            self.lp.click_login()\n    \n            # Capture Screenshot after Login\n            allure.attach(self.driver.get_screenshot_as_png(), name=f\"After_Login_{username}\",\n                          attachment_type=AttachmentType.PNG)\n    \n            # Validate Result\n            self.actual_result = self.lp.myaccount_page()\n            self.logger.info(f\"Actual: {self.actual_result}, Expected: {expected_result}\")\n            if self.actual_result.strip().lower() in [\"exceeded\",\"unknown\"]:\n                self.actual_result = \"Invalid\"\n            # Assert and Capture Failures\n            if self.actual_result.strip().lower() == expected_result.strip().lower():\n                self.logger.info(f\"Test Passed for {username}\")\n                assert True\n            else:\n                self.logger.error(f\"Test Failed for {username}\")\n                allure.attach(self.driver.get_screenshot_as_png(), name=f\"Failure_{username}\",\n                              attachment_type=AttachmentType.PNG)\n                assert False\n    \n        except Exception as e:\n            self.logger.error(f\"Unexpected error: {e}\")\n            allure.attach(self.driver.get_screenshot_as_png(), name=f\"Unexpected_Error_{username}\",\n                          attachment_type=AttachmentType.PNG)\n>           assert False\nE           assert False\n\ntestCases\\Data Driven Test\\test_004_DDT.py:64: AssertionError"}, "attachments": [{"name": "After_Login_ndj@mailinator.com", "source": "d4112d9c-bca0-41bb-9d51-fcd877bd53ee-attachment.png", "type": "image/png"}, {"name": "Failure_ndj@mailinator.com", "source": "36ae386f-aa30-430b-a87b-cce9ed1c3d02-attachment.png", "type": "image/png"}, {"name": "Unexpected_Error_ndj@mailinator.com", "source": "3c156f85-c5f7-4d87-84df-d5be6adfc2cd-attachment.png", "type": "image/png"}, {"name": "log", "source": "a4e59c49-fcd5-431e-8ee7-2e464dd056ea-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'ndj@mailinator.com'"}, {"name": "password", "value": "'a4iM2@qJaP7U4AS'"}, {"name": "expected_result", "value": "'Valid'"}], "start": 1740909822523, "stop": 1740909842768, "uuid": "5c499698-f789-4db9-936f-cd940704af24", "historyId": "5824f2dfec43c90d8f7bae3ad7be7a74", "testCaseId": "feaf2845cd517faac78063da184e07ae", "fullName": "testCases.Data Driven Test.test_004_DDT.Test_Data_Driven#test_data_driven_testing", "labels": [{"name": "parentSuite", "value": "testCases.Data Driven Test"}, {"name": "suite", "value": "test_004_DDT"}, {"name": "subSuite", "value": "Test_Data_Driven"}, {"name": "host", "value": "DESKTOP-DL1JSBI"}, {"name": "thread", "value": "2744-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCases.Data Driven Test.test_004_DDT"}]}